import type { Lang } from '@/site/types';

const fr = {
  navCarnet: 'Le Carnet',
  navPartners: 'Partenaires',
  navServices: 'Savoir-faire',
  navConcierge: 'Concierge',
  mySpace: 'Mon espace',
  themeDark: 'Mode sombre',
  themeLight: 'Mode clair',
  language: 'Langue',
  account: { signIn: 'Se connecter', space: 'Mon espace client', history: 'Mon historique', logout: 'Se déconnecter', connected: 'Connecté' },
  me: {
    eyebrow: 'Espace client',
    morning: 'Bonjour',
    evening: 'Bonsoir',
    home: 'vous êtes chez vous.',
    lead: 'Vos demandes, nos échanges et votre concierge, réunis au même endroit. Dites-nous simplement ce dont vous avez besoin.',
    robotLines: ['Re-bonjour {name} ! Ravi de vous revoir.', 'Un rappel, un suivi, une question ? Je m’en occupe.', 'Je connais déjà votre dossier, parlons-en.'],
    robotCta: 'Parler au concierge',
    robotHint: 'Votre concierge · il vous reconnaît',
    callback: 'Être rappelé',
    callbackText: 'Un membre de l’équipe vous recontacte rapidement.',
    history: 'Mon historique',
    historyText: 'Demandes, échanges et factures.',
    concierge: 'Concierge vocal',
    conciergeText: 'Il reprend là où vous vous étiez arrêté.',
    request: 'Nouvelle demande',
    requestText: 'Décrivez un besoin en quelques mots.',
    open: 'demandes en cours',
    exchanges: 'échanges avec l’équipe',
    invoices: 'factures',
    since: 'Client depuis',
    activity: 'Votre fil d’activité',
    seeAll: 'Tout voir',
    empty: 'Rien pour l’instant. Votre première demande apparaîtra ici.',
    loading: 'Chargement de votre espace…',
    error: 'Impossible de charger votre activité pour le moment.',
    requestLabel: 'Demande',
    exchangeLabel: 'Échange',
    status: { new: 'Nouveau', to_call: 'À rappeler', in_progress: 'En cours', waiting_client: 'En attente', scheduled: 'Planifié', done: 'Terminé' } as Record<string, string>,
  },

  heroEyebrow: 'Électricité · Rénovation · Projets',
  heroTitle: 'Les électriciens',
  heroSub: 'Dépannage, rénovation et installations techniques pour les maisons, copropriétés et locaux professionnels, autour de chez vous.',
  ctaCallback: 'Être rappelé par l’équipe',
  ctaWork: 'Voir nos réalisations',
  robotLines: [
    'Bonjour ! Je suis le concierge CELEC.',
    'Laissez-moi vous montrer ce qu’on fait chez CELEC.',
    'Une panne, des travaux, un projet ? Parlons-en.',
  ],
  robotCta: 'Parler au concierge',
  robotHint: 'Concierge IA · échange vocal',
  robotEntering: 'Le concierge vous accueille…',
  robotCancel: 'Annuler',
  mapChip: 'Nos projets sur la carte',

  statEntries: 'billets au Carnet',
  statCities: 'communes accompagnées',
  statPartners: 'marques partenaires',

  carnetTitle: 'Le Carnet de projets',
  carnetLead: 'Des rénovations, des installations et des espaces bien pensés, documentés sur le terrain.',
  seeAllCarnet: 'Voir tout le Carnet',
  readEntry: 'Voir le billet',

  servicesTitle: 'Ce que nous faisons',
  servicesLead: 'Trois métiers, une même exigence : comprendre l’installation avant d’y toucher.',
  services: [
    { title: 'Dépannage', text: 'Pannes, recherche de défaut, remise en service rapide et sécurisée.' },
    { title: 'Travaux & rénovation', text: 'Tableaux, lignes, mise en sécurité et remise aux normes.' },
    { title: 'Projets & installations', text: 'Éclairage, domotique, réseau : des espaces pensés pour durer.' },
  ],

  methodTitle: 'Notre méthode',
  methodText: 'On ne repart jamais de zéro. On écoute, on documente, on garde le fil.',
  methodSteps: [
    { title: 'Écouter', text: 'Comprendre vos usages avant de parler technique.' },
    { title: 'Comprendre', text: 'Lire l’installation existante et son histoire.' },
    { title: 'Documenter', text: 'Chaque intervention rejoint le Carnet.' },
    { title: 'Garder le fil', text: 'Un suivi qui vous retrouve, des années après.' },
  ],

  mapTitle: 'Autour de chez vous',
  mapLead: 'Nos interventions, là où vous vivez. Touchez une commune pour voir ses billets.',
  mapPhotos: 'photos',
  mapCities: 'communes',
  mapEmpty: 'Aucune photo pour cette commune.',

  partnersTitle: 'Avec qui nous travaillons',
  partnersLead: 'Des marques solides, choisies pour leur fiabilité sur le terrain.',
  seePartners: 'Découvrir nos partenaires',
  noPartners: 'Aucun partenaire pour le moment.',

  teamTitle: 'L’équipe',
  teamLead: 'Des électriciens qui prennent le temps d’expliquer.',
  team: [
    { name: 'Léa', role: 'Électricité & relation client', bio: 'Elle relie les détails techniques aux usages du quotidien.' },
    { name: 'Marc', role: 'Dépannage & rénovation', bio: 'Il comprend pourquoi une installation raconte une autre histoire.' },
    { name: 'Noé', role: 'Installations & éclairage', bio: 'Il pense les lignes et la lumière pour qu’elles tiennent dans le temps.' },
  ],

  contactTitle: 'Vous avez quelque chose en tête ?',
  contactLead: 'Parlons de votre projet. Notre équipe vous rappelle pour comprendre vos besoins et vous conseiller.',
  contactFor: 'Je vous contacte pour…',
  catDepannage: 'Un dépannage',
  catChantier: 'Un chantier',
  catProjet: 'Un projet',
  orType: 'Décrivez votre besoin ici…',
  voice: 'Message vocal',
  voiceStop: 'Arrêter',
  voiceRetry: 'Recommencer',
  send: 'Envoyer',
  guestPhone: 'Votre numéro de téléphone',
  orConnect: 'Se connecter pour suivre ma demande',
  noAccount: 'Sans compte obligatoire.',
  sending: 'Envoi en cours…',
  sent: 'Message envoyé. Nous revenons vers vous rapidement.',
  sentNotified: 'L’équipe est prévenue.',
  sentQueued: 'Votre demande est enregistrée.',
  sendError: 'L’envoi a échoué, réessayez dans un instant.',
  signedAs: 'Connecté en tant que',

  callbackTitle: 'On vous rappelle',
  callbackText: 'Laissez votre numéro, un électricien CELEC vous rappelle.',
  callbackSend: 'Demander un rappel',
  callbackDone: 'C’est noté, on vous rappelle très vite.',
  callbackError: 'L’envoi a échoué, réessayez dans un instant.',

  detectedBrands: 'Marques présentes',
  gallery: 'En images',
  reviews: 'Avis',
  loadReviews: 'Afficher les avis',
  noReviews: 'Pas encore d’avis. Soyez le premier.',
  writeComment: 'Écrire un avis…',
  submitReview: 'Publier',
  reviewError: 'Votre avis n’a pas pu être publié.',
  noBrandSheet: 'Marque rencontrée sur le terrain, sans fiche partenaire pour le moment.',
  relatedEntries: 'Billets liés à cette marque',
  noRelated: 'Aucun billet ne mentionne encore cette marque.',
  backToConversation: 'Revenir à la conversation',
  close: 'Fermer',

  carnetPageLead: 'Ce qu’on apprend sur le terrain, billet après billet.',
  carnetEnd: 'Tout le Carnet est affiché.',
  carnetEmpty: 'Le Carnet est vide pour le moment.',
  carnetError: 'Le Carnet n’a pas pu être chargé.',
  retry: 'Réessayer',

  blocktechNote: 'Quand le projet dépasse l’électricité classique, CELEC s’appuie sur BlockTech pour l’étude et l’architecture technique.',
  btField: 'Le terrain',
  btArch: 'L’architecture',
  btFieldItems: ['Installation', 'Dépannage', 'Électricité'],
  btArchItems: ['Étude', 'Réseau', 'Automatisme'],

  loginTitle: 'Espace CELEC',
  loginSub: 'Connexion réservée à l’équipe.',
  email: 'Email',
  password: 'Mot de passe',
  signIn: 'Se connecter',
  forgot: 'Mot de passe oublié ?',
  teamOnly: 'Accès réservé à l’équipe CELEC.',

  footer: 'Électricité de proximité',
  footerAdmin: 'Espace CELEC',
};

export type Copy = typeof fr;

const en: Copy = {
  navCarnet: 'The Notebook',
  navPartners: 'Partners',
  navServices: 'Expertise',
  navConcierge: 'Concierge',
  mySpace: 'My space',
  themeDark: 'Dark mode',
  themeLight: 'Light mode',
  language: 'Language',
  account: { signIn: 'Sign in', space: 'My client space', history: 'My history', logout: 'Sign out', connected: 'Signed in' },
  me: {
    eyebrow: 'Client space',
    morning: 'Hello',
    evening: 'Good evening',
    home: 'welcome home.',
    lead: 'Your requests, our conversations and your concierge, all in one place. Just tell us what you need.',
    robotLines: ['Welcome back {name}! Great to see you.', 'A callback, a follow-up, a question? I’ll handle it.', 'I already know your file, let’s talk.'],
    robotCta: 'Talk to the concierge',
    robotHint: 'Your concierge · it knows you',
    callback: 'Get a callback',
    callbackText: 'A team member will call you back shortly.',
    history: 'My history',
    historyText: 'Requests, exchanges and invoices.',
    concierge: 'Voice concierge',
    conciergeText: 'It picks up where you left off.',
    request: 'New request',
    requestText: 'Describe what you need in a few words.',
    open: 'open requests',
    exchanges: 'exchanges with the team',
    invoices: 'invoices',
    since: 'Client since',
    activity: 'Your activity',
    seeAll: 'See all',
    empty: 'Nothing yet. Your first request will show up here.',
    loading: 'Loading your space…',
    error: 'We couldn’t load your activity right now.',
    requestLabel: 'Request',
    exchangeLabel: 'Exchange',
    status: { new: 'New', to_call: 'To call', in_progress: 'In progress', waiting_client: 'Waiting', scheduled: 'Scheduled', done: 'Done' } as Record<string, string>,
  },
  heroEyebrow: 'Electrical · Renovation · Projects',
  heroTitle: 'The electricians',
  heroSub: 'Troubleshooting, renovation and technical installations for homes, buildings and businesses near you.',
  ctaCallback: 'Get a call back',
  ctaWork: 'See our work',
  robotLines: [
    'Hello! I am the CELEC concierge.',
    'Let me show you what we do at CELEC.',
    'A fault, some work, a project? Let’s talk.',
  ],
  robotCta: 'Talk to the concierge',
  robotHint: 'AI concierge · voice chat',
  robotEntering: 'The concierge is welcoming you…',
  robotCancel: 'Cancel',
  mapChip: 'Our projects on the map',
  statEntries: 'notebook entries',
  statCities: 'towns served',
  statPartners: 'partner brands',
  carnetTitle: 'The project Notebook',
  carnetLead: 'Renovations, installations and well-designed spaces, documented in the field.',
  seeAllCarnet: 'See the whole Notebook',
  readEntry: 'Read the entry',
  servicesTitle: 'What we do',
  servicesLead: 'Three trades, one standard: understand the installation before touching it.',
  services: [
    { title: 'Troubleshooting', text: 'Faults, diagnosis, fast and safe restoration.' },
    { title: 'Renovation', text: 'Panels, circuits, safety upgrades and compliance.' },
    { title: 'Projects & installations', text: 'Lighting, home automation, network: spaces built to last.' },
  ],
  methodTitle: 'Our method',
  methodText: 'We never start from scratch. We listen, document and keep the thread.',
  methodSteps: [
    { title: 'Listen', text: 'Understand how you live before talking tech.' },
    { title: 'Understand', text: 'Read the existing installation and its history.' },
    { title: 'Document', text: 'Every job joins the Notebook.' },
    { title: 'Keep the thread', text: 'Follow-up that finds you, years later.' },
  ],
  mapTitle: 'Around you',
  mapLead: 'Our work, where you live. Tap a town to see its entries.',
  mapPhotos: 'photos',
  mapCities: 'towns',
  mapEmpty: 'No photo for this town.',
  partnersTitle: 'Who we work with',
  partnersLead: 'Solid brands, chosen for their reliability in the field.',
  seePartners: 'Discover our partners',
  noPartners: 'No partners yet.',
  teamTitle: 'The team',
  teamLead: 'Electricians who take the time to explain.',
  team: [
    { name: 'Léa', role: 'Electrical & client relations', bio: 'She connects technical details to everyday life.' },
    { name: 'Marc', role: 'Troubleshooting & renovation', bio: 'He understands why an installation tells another story.' },
    { name: 'Noé', role: 'Installations & lighting', bio: 'He designs circuits and light that stand the test of time.' },
  ],
  contactTitle: 'Something on your mind?',
  contactLead: 'Tell us about your project. Our team calls you back to understand your needs and advise you.',
  contactFor: 'I’m contacting you for…',
  catDepannage: 'A repair',
  catChantier: 'A renovation',
  catProjet: 'A project',
  orType: 'Describe your need here…',
  voice: 'Voice message',
  voiceStop: 'Stop',
  voiceRetry: 'Start over',
  send: 'Send',
  guestPhone: 'Your phone number',
  orConnect: 'Sign in to follow my request',
  noAccount: 'No account required.',
  sending: 'Sending…',
  sent: 'Message sent. We’ll get back to you soon.',
  sentNotified: 'The team has been notified.',
  sentQueued: 'Your request is saved.',
  sendError: 'Sending failed, please try again shortly.',
  signedAs: 'Signed in as',
  callbackTitle: 'We’ll call you back',
  callbackText: 'Leave your number and a CELEC electrician will call you back.',
  callbackSend: 'Request a call back',
  callbackDone: 'Noted, we’ll call you back very soon.',
  callbackError: 'Sending failed, please try again shortly.',
  detectedBrands: 'Brands on site',
  gallery: 'In pictures',
  reviews: 'Reviews',
  loadReviews: 'Show reviews',
  noReviews: 'No reviews yet. Be the first.',
  writeComment: 'Write a review…',
  submitReview: 'Publish',
  reviewError: 'Your review could not be published.',
  noBrandSheet: 'A brand met in the field, without a partner sheet yet.',
  relatedEntries: 'Entries featuring this brand',
  noRelated: 'No entry mentions this brand yet.',
  backToConversation: 'Back to the conversation',
  close: 'Close',
  carnetPageLead: 'What we learn in the field, one entry at a time.',
  carnetEnd: 'The whole Notebook is displayed.',
  carnetEmpty: 'The Notebook is empty for now.',
  carnetError: 'The Notebook could not be loaded.',
  retry: 'Try again',
  blocktechNote: 'When a project goes beyond standard electrical work, CELEC relies on BlockTech for engineering and technical architecture.',
  btField: 'The field',
  btArch: 'The architecture',
  btFieldItems: ['Installation', 'Troubleshooting', 'Electrical'],
  btArchItems: ['Engineering', 'Network', 'Automation'],
  loginTitle: 'CELEC Area',
  loginSub: 'Team access only.',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  forgot: 'Forgot your password?',
  teamOnly: 'Access reserved for the CELEC team.',
  footer: 'Local electrical services',
  footerAdmin: 'CELEC Area',
};

const es: Copy = {
  navCarnet: 'El Cuaderno',
  navPartners: 'Socios',
  navServices: 'Oficio',
  navConcierge: 'Conserje',
  mySpace: 'Mi espacio',
  themeDark: 'Modo oscuro',
  themeLight: 'Modo claro',
  language: 'Idioma',
  account: { signIn: 'Iniciar sesión', space: 'Mi espacio cliente', history: 'Mi historial', logout: 'Cerrar sesión', connected: 'Conectado' },
  me: {
    eyebrow: 'Espacio cliente',
    morning: 'Hola',
    evening: 'Buenas noches',
    home: 'está en casa.',
    lead: 'Sus solicitudes, nuestros intercambios y su conserje, en un solo lugar. Díganos simplemente lo que necesita.',
    robotLines: ['¡Hola de nuevo {name}! Encantado de verle.', '¿Una llamada, un seguimiento, una pregunta? Me encargo.', 'Ya conozco su expediente, hablemos.'],
    robotCta: 'Hablar con el conserje',
    robotHint: 'Su conserje · le reconoce',
    callback: 'Que me llamen',
    callbackText: 'Un miembro del equipo le llamará pronto.',
    history: 'Mi historial',
    historyText: 'Solicitudes, intercambios y facturas.',
    concierge: 'Conserje por voz',
    conciergeText: 'Retoma donde lo dejó.',
    request: 'Nueva solicitud',
    requestText: 'Describa su necesidad en pocas palabras.',
    open: 'solicitudes en curso',
    exchanges: 'intercambios con el equipo',
    invoices: 'facturas',
    since: 'Cliente desde',
    activity: 'Su actividad',
    seeAll: 'Ver todo',
    empty: 'Nada por ahora. Su primera solicitud aparecerá aquí.',
    loading: 'Cargando su espacio…',
    error: 'No pudimos cargar su actividad por ahora.',
    requestLabel: 'Solicitud',
    exchangeLabel: 'Intercambio',
    status: { new: 'Nuevo', to_call: 'Por llamar', in_progress: 'En curso', waiting_client: 'En espera', scheduled: 'Planificado', done: 'Terminado' } as Record<string, string>,
  },
  heroEyebrow: 'Electricidad · Renovación · Proyectos',
  heroTitle: 'Los electricistas',
  heroSub: 'Reparaciones, renovación e instalaciones técnicas para viviendas, comunidades y locales profesionales, cerca de usted.',
  ctaCallback: 'Que me llame el equipo',
  ctaWork: 'Ver nuestros trabajos',
  robotLines: [
    '¡Hola! Soy el conserje de CELEC.',
    'Déjeme mostrarle lo que hacemos en CELEC.',
    '¿Una avería, obras, un proyecto? Hablemos.',
  ],
  robotCta: 'Hablar con el conserje',
  robotHint: 'Conserje IA · conversación por voz',
  robotEntering: 'El conserje le da la bienvenida…',
  robotCancel: 'Cancelar',
  mapChip: 'Nuestros proyectos en el mapa',
  statEntries: 'entradas en el Cuaderno',
  statCities: 'municipios atendidos',
  statPartners: 'marcas asociadas',
  carnetTitle: 'El Cuaderno de proyectos',
  carnetLead: 'Renovaciones, instalaciones y espacios bien pensados, documentados sobre el terreno.',
  seeAllCarnet: 'Ver todo el Cuaderno',
  readEntry: 'Ver la entrada',
  servicesTitle: 'Lo que hacemos',
  servicesLead: 'Tres oficios, una misma exigencia: entender la instalación antes de tocarla.',
  services: [
    { title: 'Reparaciones', text: 'Averías, diagnóstico, puesta en servicio rápida y segura.' },
    { title: 'Obras y renovación', text: 'Cuadros, líneas, seguridad y adecuación a la normativa.' },
    { title: 'Proyectos e instalaciones', text: 'Iluminación, domótica, red: espacios pensados para durar.' },
  ],
  methodTitle: 'Nuestro método',
  methodText: 'Nunca empezamos de cero. Escuchamos, documentamos y mantenemos el hilo.',
  methodSteps: [
    { title: 'Escuchar', text: 'Entender sus usos antes de hablar de técnica.' },
    { title: 'Comprender', text: 'Leer la instalación existente y su historia.' },
    { title: 'Documentar', text: 'Cada intervención se suma al Cuaderno.' },
    { title: 'Mantener el hilo', text: 'Un seguimiento que le encuentra, años después.' },
  ],
  mapTitle: 'Cerca de usted',
  mapLead: 'Nuestras intervenciones, donde usted vive. Toque un municipio para ver sus entradas.',
  mapPhotos: 'fotos',
  mapCities: 'municipios',
  mapEmpty: 'Ninguna foto para este municipio.',
  partnersTitle: 'Con quién trabajamos',
  partnersLead: 'Marcas sólidas, elegidas por su fiabilidad sobre el terreno.',
  seePartners: 'Descubrir nuestros socios',
  noPartners: 'Todavía no hay socios.',
  teamTitle: 'El equipo',
  teamLead: 'Electricistas que se toman el tiempo de explicar.',
  team: [
    { name: 'Léa', role: 'Electricidad y atención al cliente', bio: 'Relaciona los detalles técnicos con la vida diaria.' },
    { name: 'Marc', role: 'Reparaciones y renovación', bio: 'Entiende por qué una instalación cuenta otra historia.' },
    { name: 'Noé', role: 'Instalaciones e iluminación', bio: 'Diseña líneas y luz que resisten el paso del tiempo.' },
  ],
  contactTitle: '¿Tiene algo en mente?',
  contactLead: 'Hablemos de su proyecto. Nuestro equipo le llama para entender sus necesidades y aconsejarle.',
  contactFor: 'Les contacto por…',
  catDepannage: 'Una avería',
  catChantier: 'Una obra',
  catProjet: 'Un proyecto',
  orType: 'Describa su necesidad aquí…',
  voice: 'Mensaje de voz',
  voiceStop: 'Parar',
  voiceRetry: 'Reintentar',
  send: 'Enviar',
  guestPhone: 'Su número de teléfono',
  orConnect: 'Iniciar sesión para seguir mi solicitud',
  noAccount: 'Sin cuenta obligatoria.',
  sending: 'Enviando…',
  sent: 'Mensaje enviado. Le responderemos pronto.',
  sentNotified: 'El equipo ha sido avisado.',
  sentQueued: 'Su solicitud ha quedado registrada.',
  sendError: 'El envío ha fallado, inténtelo de nuevo en un momento.',
  signedAs: 'Conectado como',
  callbackTitle: 'Le devolvemos la llamada',
  callbackText: 'Deje su número y un electricista de CELEC le llamará.',
  callbackSend: 'Solicitar una llamada',
  callbackDone: 'Anotado, le llamamos muy pronto.',
  callbackError: 'El envío ha fallado, inténtelo de nuevo en un momento.',
  detectedBrands: 'Marcas presentes',
  gallery: 'En imágenes',
  reviews: 'Opiniones',
  loadReviews: 'Ver las opiniones',
  noReviews: 'Aún no hay opiniones. Sea el primero.',
  writeComment: 'Escribir una opinión…',
  submitReview: 'Publicar',
  reviewError: 'Su opinión no se ha podido publicar.',
  noBrandSheet: 'Marca encontrada sobre el terreno, todavía sin ficha de socio.',
  relatedEntries: 'Entradas con esta marca',
  noRelated: 'Ninguna entrada menciona todavía esta marca.',
  backToConversation: 'Volver a la conversación',
  close: 'Cerrar',
  carnetPageLead: 'Lo que aprendemos sobre el terreno, entrada tras entrada.',
  carnetEnd: 'Se muestra todo el Cuaderno.',
  carnetEmpty: 'El Cuaderno está vacío por ahora.',
  carnetError: 'No se ha podido cargar el Cuaderno.',
  retry: 'Reintentar',
  blocktechNote: 'Cuando un proyecto va más allá de la electricidad clásica, CELEC se apoya en BlockTech para el estudio y la arquitectura técnica.',
  btField: 'El terreno',
  btArch: 'La arquitectura',
  btFieldItems: ['Instalación', 'Reparación', 'Electricidad'],
  btArchItems: ['Estudio', 'Red', 'Automatización'],
  loginTitle: 'Espacio CELEC',
  loginSub: 'Acceso reservado al equipo.',
  email: 'Email',
  password: 'Contraseña',
  signIn: 'Iniciar sesión',
  forgot: '¿Ha olvidado su contraseña?',
  teamOnly: 'Acceso reservado al equipo CELEC.',
  footer: 'Electricidad de proximidad',
  footerAdmin: 'Espacio CELEC',
};

const ar: Copy = {
  navCarnet: 'الدفتر',
  navPartners: 'الشركاء',
  navServices: 'خبرتنا',
  navConcierge: 'المساعد',
  mySpace: 'مساحتي',
  themeDark: 'الوضع الداكن',
  themeLight: 'الوضع الفاتح',
  language: 'اللغة',
  account: { signIn: 'تسجيل الدخول', space: 'مساحة العميل', history: 'سجلي', logout: 'تسجيل الخروج', connected: 'متصل' },
  me: {
    eyebrow: 'مساحة العميل',
    morning: 'مرحباً',
    evening: 'مساء الخير',
    home: 'أنت في بيتك.',
    lead: 'طلباتك ومحادثاتنا ومساعدك في مكان واحد. أخبرنا فقط بما تحتاجه.',
    robotLines: ['أهلاً بعودتك {name}! سعيد برؤيتك.', 'اتصال أو متابعة أو سؤال؟ أنا أتولى الأمر.', 'أعرف ملفك مسبقاً، لنتحدث.'],
    robotCta: 'تحدث مع المساعد',
    robotHint: 'مساعدك · يتعرف عليك',
    callback: 'اطلب اتصالاً',
    callbackText: 'سيتصل بك أحد أعضاء الفريق قريباً.',
    history: 'سجلي',
    historyText: 'الطلبات والمحادثات والفواتير.',
    concierge: 'المساعد الصوتي',
    conciergeText: 'يكمل من حيث توقفت.',
    request: 'طلب جديد',
    requestText: 'صف حاجتك ببضع كلمات.',
    open: 'طلبات جارية',
    exchanges: 'محادثات مع الفريق',
    invoices: 'فواتير',
    since: 'عميل منذ',
    activity: 'نشاطك',
    seeAll: 'عرض الكل',
    empty: 'لا شيء حالياً. سيظهر طلبك الأول هنا.',
    loading: 'جارٍ تحميل مساحتك…',
    error: 'تعذر تحميل نشاطك حالياً.',
    requestLabel: 'طلب',
    exchangeLabel: 'محادثة',
    status: { new: 'جديد', to_call: 'للاتصال', in_progress: 'قيد التنفيذ', waiting_client: 'في الانتظار', scheduled: 'مجدول', done: 'منتهٍ' } as Record<string, string>,
  },
  heroEyebrow: 'كهرباء · تجديد · مشاريع',
  heroTitle: 'كهربائيو',
  heroSub: 'إصلاحات وتجديد وتركيبات تقنية للمنازل والعمارات والمحلات المهنية، بالقرب منكم.',
  ctaCallback: 'اطلب اتصالاً من الفريق',
  ctaWork: 'شاهد أعمالنا',
  robotLines: [
    'مرحباً! أنا مساعد CELEC.',
    'دعني أريك ما نقوم به في CELEC.',
    'عطل، أشغال، مشروع؟ لنتحدث.',
  ],
  robotCta: 'تحدث مع المساعد',
  robotHint: 'مساعد ذكي · محادثة صوتية',
  robotEntering: 'المساعد يرحب بك…',
  robotCancel: 'إلغاء',
  mapChip: 'مشاريعنا على الخريطة',
  statEntries: 'تدوينة في الدفتر',
  statCities: 'بلدية مخدومة',
  statPartners: 'علامة شريكة',
  carnetTitle: 'دفتر المشاريع',
  carnetLead: 'تجديدات وتركيبات ومساحات مدروسة، موثقة في الميدان.',
  seeAllCarnet: 'شاهد الدفتر كاملاً',
  readEntry: 'اقرأ التدوينة',
  servicesTitle: 'ما نقوم به',
  servicesLead: 'ثلاث مهن، ومعيار واحد: فهم التركيب قبل لمسه.',
  services: [
    { title: 'إصلاحات', text: 'أعطال، تشخيص، وإعادة تشغيل سريعة وآمنة.' },
    { title: 'أشغال وتجديد', text: 'لوحات، خطوط، تأمين ومطابقة للمعايير.' },
    { title: 'مشاريع وتركيبات', text: 'إنارة، منزل ذكي، شبكة: مساحات مصممة لتدوم.' },
  ],
  methodTitle: 'طريقتنا',
  methodText: 'لا نبدأ من الصفر أبداً. نستمع، نوثق، ونحافظ على الخيط.',
  methodSteps: [
    { title: 'الاستماع', text: 'فهم استخداماتك قبل الحديث التقني.' },
    { title: 'الفهم', text: 'قراءة التركيب الحالي وتاريخه.' },
    { title: 'التوثيق', text: 'كل تدخل ينضم إلى الدفتر.' },
    { title: 'الحفاظ على الخيط', text: 'متابعة تجدك حتى بعد سنوات.' },
  ],
  mapTitle: 'بالقرب منكم',
  mapLead: 'تدخلاتنا حيث تعيشون. اختر بلدية لرؤية تدويناتها.',
  mapPhotos: 'صور',
  mapCities: 'بلديات',
  mapEmpty: 'لا توجد صور لهذه البلدية.',
  partnersTitle: 'مع من نعمل',
  partnersLead: 'علامات متينة، مختارة لموثوقيتها في الميدان.',
  seePartners: 'اكتشف شركاءنا',
  noPartners: 'لا يوجد شركاء حالياً.',
  teamTitle: 'الفريق',
  teamLead: 'كهربائيون يأخذون الوقت للشرح.',
  team: [
    { name: 'Léa', role: 'كهرباء وعلاقات العملاء', bio: 'تربط التفاصيل التقنية بالاستخدام اليومي.' },
    { name: 'Marc', role: 'إصلاحات وتجديد', bio: 'يفهم لماذا يروي كل تركيب قصة مختلفة.' },
    { name: 'Noé', role: 'تركيبات وإنارة', bio: 'يصمم الخطوط والإضاءة لتدوم مع الزمن.' },
  ],
  contactTitle: 'هل لديك فكرة ما؟',
  contactLead: 'لنتحدث عن مشروعك. فريقنا يعاود الاتصال بك لفهم احتياجاتك وتقديم النصيحة.',
  contactFor: 'أتواصل معكم بشأن…',
  catDepannage: 'إصلاح',
  catChantier: 'أشغال',
  catProjet: 'مشروع',
  orType: 'صف حاجتك هنا…',
  voice: 'رسالة صوتية',
  voiceStop: 'إيقاف',
  voiceRetry: 'إعادة',
  send: 'إرسال',
  guestPhone: 'رقم هاتفك',
  orConnect: 'سجل الدخول لمتابعة طلبي',
  noAccount: 'دون الحاجة إلى حساب.',
  sending: 'جارٍ الإرسال…',
  sent: 'تم إرسال الرسالة. سنعود إليك قريباً.',
  sentNotified: 'تم إبلاغ الفريق.',
  sentQueued: 'تم تسجيل طلبك.',
  sendError: 'فشل الإرسال، حاول مجدداً بعد قليل.',
  signedAs: 'متصل باسم',
  callbackTitle: 'سنعاود الاتصال بك',
  callbackText: 'اترك رقمك وسيتصل بك كهربائي من CELEC.',
  callbackSend: 'اطلب معاودة الاتصال',
  callbackDone: 'تم، سنتصل بك قريباً جداً.',
  callbackError: 'فشل الإرسال، حاول مجدداً بعد قليل.',
  detectedBrands: 'العلامات الموجودة',
  gallery: 'بالصور',
  reviews: 'الآراء',
  loadReviews: 'عرض الآراء',
  noReviews: 'لا توجد آراء بعد. كن الأول.',
  writeComment: 'اكتب رأيك…',
  submitReview: 'نشر',
  reviewError: 'تعذر نشر رأيك.',
  noBrandSheet: 'علامة صادفناها في الميدان، دون بطاقة شريك حالياً.',
  relatedEntries: 'تدوينات مرتبطة بهذه العلامة',
  noRelated: 'لا توجد تدوينة تذكر هذه العلامة بعد.',
  backToConversation: 'العودة إلى المحادثة',
  close: 'إغلاق',
  carnetPageLead: 'ما نتعلمه في الميدان، تدوينة بعد تدوينة.',
  carnetEnd: 'تم عرض الدفتر كاملاً.',
  carnetEmpty: 'الدفتر فارغ حالياً.',
  carnetError: 'تعذر تحميل الدفتر.',
  retry: 'إعادة المحاولة',
  blocktechNote: 'عندما يتجاوز المشروع الكهرباء التقليدية، يعتمد CELEC على BlockTech للدراسة والهندسة التقنية.',
  btField: 'الميدان',
  btArch: 'الهندسة',
  btFieldItems: ['تركيب', 'إصلاح', 'كهرباء'],
  btArchItems: ['دراسة', 'شبكة', 'أتمتة'],
  loginTitle: 'فضاء CELEC',
  loginSub: 'دخول مخصص للفريق.',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  signIn: 'تسجيل الدخول',
  forgot: 'نسيت كلمة المرور؟',
  teamOnly: 'الدخول مخصص لفريق CELEC.',
  footer: 'كهرباء القرب',
  footerAdmin: 'فضاء CELEC',
};

export const copy: Record<Lang, Copy> = { fr, en, es, ar };

export const languages: { code: Lang; short: string; label: string }[] = [
  { code: 'fr', short: 'FR', label: 'Français' },
  { code: 'en', short: 'EN', label: 'English' },
  { code: 'es', short: 'ES', label: 'Español' },
  { code: 'ar', short: 'AR', label: 'العربية' },
];

export const IMAGES = {
  hero: 'https://images.pexels.com/photos/22743854/pexels-photo-22743854.jpeg?auto=compress&cs=tinysrgb&w=1400',
  heroDetail: 'https://images.pexels.com/photos/31206787/pexels-photo-31206787.jpeg?auto=compress&cs=tinysrgb&w=700',
  services: [
    'https://images.pexels.com/photos/34054464/pexels-photo-34054464.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/9679179/pexels-photo-9679179.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/1534124/pexels-photo-1534124.jpeg?auto=compress&cs=tinysrgb&w=900',
  ],
  contact: 'https://images.pexels.com/photos/6580378/pexels-photo-6580378.jpeg?auto=compress&cs=tinysrgb&w=1600',
};
